import Tests.Framework
import Tests.Prng
import Tests.Praw

/-!
# png-decode tests

PNG decode incl. PngSuite corpus and corrupt-file errors. Owned by WP12.

* `pngsuiteSweepTest`/`pngsuiteCorruptTest` — THE acceptance test: every
  `.praw` truth fixture under `testdata/corpus/pngsuite-truth/` must match
  `decode` on the corresponding vendored PngSuite `.png`, and every file
  named in `testdata/corpus/pngsuite/CORRUPT.txt` must fail to decode
  (chunk-layer or decode-layer errors both count — only a panic/hang would
  be a failure).
* `pillowGoldenSweepTest` — every `testdata/golden/*.png` this work
  package's own encoder (WP11) or the Pillow oracle produced decodes back
  to pixel-exact agreement with its `.praw` twin.
* `selfRoundTripTests` — `decode(Png.encode img) == img` pixel-exact
  across every mode and three sizes, no external fixtures involved.
* `truncationFuzzTest` — every prefix (stride 11) of a mid-size golden PNG
  is rejected with `.error`, never a panic or a hang.
* `ancillarySpotCheckTests` — exact `tEXt`/`gAMA` values cross-checked
  against Pillow for two PngSuite fixtures.
-/

namespace Tests.PngDecodeTests

open PILean

/-- Vendored PngSuite corpus directory. -/
def pngsuiteDir : System.FilePath := System.FilePath.mk "testdata" / "corpus" / "pngsuite"

/-- Pixel-truth `.praw` fixtures for the PngSuite corpus, generated by
`testdata/py/pngsuite_truth.py`. -/
def pngsuiteTruthDir : System.FilePath := System.FilePath.mk "testdata" / "corpus" / "pngsuite-truth"

/-- Join `xs` with newlines, without depending on `String.intercalate`. -/
private def joinLines (xs : List String) : String :=
  xs.foldl (init := "") fun acc x => if acc.isEmpty then x else acc ++ "\n" ++ x

/-- THE acceptance test: decode every vendored PngSuite `.png` that has a
committed pixel-truth `.praw` and require pixel-exact agreement,
collecting *every* failing filename (rather than stopping at the first)
so a broken run reports the whole picture at once. -/
def pngsuiteSweepTest : TestCase :=
  test "pngsuite sweep: decode(.png) matches the Pillow-oracle .praw truth" do
    let entries ← pngsuiteTruthDir.readDir
    let prawEntries := entries.filter fun e => e.fileName.endsWith ".praw"
    assertTrue (prawEntries.size > 0) "expected committed PngSuite .praw truth fixtures to exist"
    let mut failures : List String := []
    for e in prawEntries do
      match e.path.fileStem with
      | none => failures := failures ++ [s!"{e.path}: no file stem"]
      | some stem =>
        let pngPath := pngsuiteDir / s!"{stem}.png"
        let expected ← Tests.Praw.load e.path
        let bytes ← IO.FS.readBinFile pngPath
        match PILean.Png.decode bytes with
        | .error err => failures := failures ++ [s!"{stem}: decode failed: {err}"]
        | .ok img =>
          try
            assertImagesEq img expected stem
          catch err =>
            failures := failures ++ [s!"{stem}: {err}"]
    assertTrue failures.isEmpty
      s!"{failures.length}/{prawEntries.size} PngSuite file(s) failed:\n{joinLines failures}"

/-- Every file PngSuite marks corrupt (`testdata/corpus/pngsuite/CORRUPT.txt`)
must fail to decode — at the chunk/CRC layer or the decode layer, either
counts as a pass; only a panic or a hang is a failure. -/
def pngsuiteCorruptTest : TestCase :=
  test "pngsuite CORRUPT.txt entries all fail to decode" do
    let text ← IO.FS.readFile (pngsuiteDir / "CORRUPT.txt")
    let names := (text.splitOn "\n").filter fun l => !l.isEmpty && !(l.startsWith "#")
    assertTrue (names.length > 0) "expected CORRUPT.txt to list at least one corrupt file"
    let mut failures : List String := []
    for name in names do
      let bytes ← IO.FS.readBinFile (pngsuiteDir / name)
      match PILean.Png.decode bytes with
      | .error _ => pure ()
      | .ok _ => failures := failures ++ [s!"{name}: expected decode to fail, but it succeeded"]
    assertTrue failures.isEmpty
      s!"{failures.length} corrupt file(s) unexpectedly decoded successfully:\n{joinLines failures}"

/-- Every committed golden `.png` with a matching `.praw` twin (the whole
pattern matrix from `testdata/py/gen_golden.py`, i.e. our own encoder's
and/or Pillow's output) decodes to pixel-exact agreement with that twin. -/
def pillowGoldenSweepTest : TestCase :=
  test "golden sweep: every testdata/golden/*.png matches its .praw twin" do
    let entries ← Tests.goldenDir.readDir
    let pngEntries := entries.filter fun e => e.fileName.endsWith ".png"
    assertTrue (pngEntries.size > 0) "expected committed golden .png fixtures to exist"
    let mut failures : List String := []
    let mut checked := 0
    for e in pngEntries do
      match e.path.fileStem with
      | none => failures := failures ++ [s!"{e.path}: no file stem"]
      | some stem =>
        let prawPath := Tests.goldenDir / s!"{stem}.praw"
        if ← prawPath.pathExists then
          checked := checked + 1
          let expected ← Tests.Praw.load prawPath
          let bytes ← IO.FS.readBinFile e.path
          match PILean.Png.decode bytes with
          | .error err => failures := failures ++ [s!"{stem}: decode failed: {err}"]
          | .ok img =>
            try
              assertImagesEq img expected stem
            catch err =>
              failures := failures ++ [s!"{stem}: {err}"]
    assertTrue (checked > 0) "expected at least one golden .png with a matching .praw twin"
    assertTrue failures.isEmpty s!"{failures.length}/{checked} golden PNG(s) failed:\n{joinLines failures}"

/-- `decode(encode img) == img` pixel-exact, across every mode and three
sizes (including the `1×1` and non-square `33×17` edge cases). Uses
`SplitMix64`-seeded random images (`.palette` images already come out of
`SplitMix64.image` with indices reduced mod 216 into the web-safe
palette, i.e. "quantized noise" with an exact ≤ 256-entry palette). -/
def selfRoundTripTests : List TestCase :=
  let modes : List Mode := [.gray, .grayAlpha, .rgb, .rgba, .palette]
  let sizes : List (Nat × Nat) := [(1, 1), (16, 16), (33, 17)]
  modes.flatMap fun mode =>
    sizes.map fun (w, h) =>
      test s!"self round trip ({mode}, {w}x{h})" do
        let (img, _) := (SplitMix64.ofSeed (7000 + mode.bytesPerPixel * 131 + w * 17 + h)).image w h mode
        match PILean.Png.encode img with
        | .error e => fail s!"{mode} {w}x{h}: encode failed: {e}"
        | .ok bytes =>
          match PILean.Png.decode bytes with
          | .error e => fail s!"{mode} {w}x{h}: decode failed: {e}"
          | .ok img' => assertImagesEq img' img s!"{mode} {w}x{h} round trip"

/-- Every prefix (stride 11 bytes) of a mid-size golden PNG (`noise` —
poorly-compressible, so its `IDAT` is large enough to give truncation
points across many different structural boundaries: signature, chunk
header, zlib header, DEFLATE body, CRC) is rejected with `.error`, never
a panic or a hang. -/
def truncationFuzzTest : TestCase :=
  test "truncation fuzz: every prefix (stride 11) of a golden PNG errors" do
    let bytes ← IO.FS.readBinFile (Tests.goldenDir / "noise_rgba_33x17.png")
    assertTrue (bytes.size > 100) "expected a non-trivial fixture to fuzz"
    let mut failures : List String := []
    for n in List.range (bytes.size / 11 + 2) do
      let len := n * 11
      if len < bytes.size then
        match PILean.Png.decode (bytes.extract 0 len) with
        | .error _ => pure ()
        | .ok _ => failures := failures ++ [s!"prefix length {len} unexpectedly decoded successfully"]
    assertTrue failures.isEmpty s!"{failures.length} truncation(s) unexpectedly succeeded:\n{joinLines failures}"

/-- Does `info` contain the pair `(key, value)`? (Avoids depending on a
`BEq (String × String)` instance existing.) -/
private def hasInfo (info : List (String × String)) (key value : String) : Bool :=
  info.any fun (k, v) => k == key && v == value

/-- Exact `tEXt`/`gAMA` values, cross-checked against Pillow, for two
PngSuite fixtures chosen for ancillary-chunk coverage: `ct1n0g04.png`
(six `tEXt` entries) and `g05n2c08.png` (a non-default `gAMA`). -/
def ancillarySpotCheckTests : List TestCase :=
  [ test "ct1n0g04.png: tEXt + gAMA parse into Image.info" do
      let bytes ← IO.FS.readBinFile (pngsuiteDir / "ct1n0g04.png")
      match PILean.Png.decode bytes with
      | .error e => fail s!"decode failed: {e}"
      | .ok img =>
        assertTrue (hasInfo img.info "Title" "PngSuite") "Title"
        assertTrue (hasInfo img.info "Author" "Willem A.J. van Schaik\n(willem@schaik.com)") "Author"
        assertTrue (hasInfo img.info "Copyright" "Copyright Willem van Schaik, Singapore 1995-96") "Copyright"
        assertTrue (hasInfo img.info "Description"
          ("A compilation of a set of images created to test the\n" ++
           "various color-types of the PNG format. Included are\n" ++
           "black&white, color, paletted, with alpha channel, with\n" ++
           "transparency formats. All bit-depths allowed according\n" ++
           "to the spec are present.")) "Description"
        assertTrue (hasInfo img.info "Software" "Created on a NeXTstation color using \"pnmtopng\".") "Software"
        assertTrue (hasInfo img.info "Disclaimer" "Freeware.") "Disclaimer"
        assertTrue (hasInfo img.info "gAMA" "100000") "gAMA"

  , test "g05n2c08.png: gAMA parses as the raw 100000-scaled integer" do
      let bytes ← IO.FS.readBinFile (pngsuiteDir / "g05n2c08.png")
      match PILean.Png.decode bytes with
      | .error e => fail s!"decode failed: {e}"
      | .ok img => assertTrue (hasInfo img.info "gAMA" "55000") "gAMA"
  ]

/-- The `png-decode` suite (WP12). -/
def suite : Tests.Suite :=
  { name := "png-decode"
    cases :=
      [pngsuiteSweepTest, pngsuiteCorruptTest, pillowGoldenSweepTest, truncationFuzzTest] ++
      selfRoundTripTests ++ ancillarySpotCheckTests }

end Tests.PngDecodeTests
