import PILean.Binary.Writer

/-!
# Bitmap fonts

Fixed-cell bitmap fonts for `Draw.text`. v1 constraint: glyphs are at most
8 pixels wide — one byte per row per glyph, MSB = leftmost pixel.
`BitmapFont.default` (Spleen 8x16, BSD-2-Clause) is generated by
`scripts/mk_font.py` as a hex string — never as an array literal — and
lives in `PILean.Font.Spleen8x16`, which decodes it via `hexToByteArray`.
-/

namespace PILean

/-- A fixed-cell bitmap font covering codepoints
`[firstCode, firstCode + count)`. `bitmap` holds `glyphHeight` bytes per
glyph, one byte per row, MSB = leftmost pixel (glyphs ≤ 8 px wide in v1). -/
structure BitmapFont where
  glyphWidth : Nat
  glyphHeight : Nat
  firstCode : Nat
  count : Nat
  bitmap : ByteArray
  deriving Inhabited

namespace BitmapFont

/-- The row bytes of `c`'s glyph, or `none` if the font doesn't cover it
(renderers draw a fallback box for `none`). -/
def glyph? (f : BitmapFont) (c : Char) : Option ByteArray :=
  let cp := c.toNat
  if f.firstCode ≤ cp && cp < f.firstCode + f.count then
    some (f.bitmap.extract ((cp - f.firstCode) * f.glyphHeight)
                           ((cp - f.firstCode + 1) * f.glyphHeight))
  else none

end BitmapFont

private def hexDigit! (c : Char) : UInt8 :=
  if '0' ≤ c && c ≤ '9' then UInt8.ofNat (c.toNat - '0'.toNat)
  else if 'a' ≤ c && c ≤ 'f' then UInt8.ofNat (c.toNat - 'a'.toNat + 10)
  else if 'A' ≤ c && c ≤ 'F' then UInt8.ofNat (c.toNat - 'A'.toNat + 10)
  else panic! s!"PILean.hexToByteArray: invalid hex digit {repr c}"

/-- Decode a hex string into bytes, tolerant of interspersed whitespace and
newlines (so generated font blobs can be wrapped for readability). Two hex
digits per byte, most-significant nibble first. Malformed digits panic —
this is only ever called on trusted, compile-time-embedded data. -/
def hexToByteArray (s : String) : ByteArray := Id.run do
  let mut nibbles : Array UInt8 := #[]
  for c in s.toList do
    unless c.isWhitespace do
      nibbles := nibbles.push (hexDigit! c)
  let mut out := ByteArray.emptyWithCapacity (nibbles.size / 2)
  let mut i := 0
  while i + 1 < nibbles.size do
    out := out.push (nibbles[i]! <<< 4 ||| nibbles[i + 1]!)
    i := i + 2
  return out

end PILean
