import PILean.Binary.Writer

/-!
# Bitmap fonts

Fixed-cell bitmap fonts for `Draw.text`. v1 constraint: glyphs are at most
8 pixels wide — one byte per row per glyph, MSB = leftmost pixel.
`BitmapFont.default` ships blank until WP6 embeds the real font
(Spleen 8x16, BSD-2-Clause, generated by `scripts/mk_font.py` as a hex
string — never as an array literal).
-/

namespace PILean

/-- A fixed-cell bitmap font covering codepoints
`[firstCode, firstCode + count)`. `bitmap` holds `glyphHeight` bytes per
glyph, one byte per row, MSB = leftmost pixel (glyphs ≤ 8 px wide in v1). -/
structure BitmapFont where
  glyphWidth : Nat
  glyphHeight : Nat
  firstCode : Nat
  count : Nat
  bitmap : ByteArray
  deriving Inhabited

namespace BitmapFont

/-- The row bytes of `c`'s glyph, or `none` if the font doesn't cover it
(renderers draw a fallback box for `none`). -/
def glyph? (f : BitmapFont) (c : Char) : Option ByteArray :=
  let cp := c.toNat
  if f.firstCode ≤ cp && cp < f.firstCode + f.count then
    some (f.bitmap.extract ((cp - f.firstCode) * f.glyphHeight)
                           ((cp - f.firstCode + 1) * f.glyphHeight))
  else none

/-- The default font: 8×16 cell, ASCII+Latin-1. Blank glyphs until WP6
embeds Spleen 8x16. -/
def default : BitmapFont :=
  ⟨8, 16, 32, 95, ByteArray.replicateByte (95 * 16) 0⟩

end BitmapFont

end PILean
