#!/usr/bin/env python3
"""
Generate PILean's golden test fixtures under `testdata/golden/` using Pillow
11.3.0 as the correctness oracle, plus the PngSuite pixel-truth corpus
under `testdata/corpus/pngsuite-truth/`.

Everything here is deterministic: every random draw goes through a
`random.Random(seed)` seeded from the table in `PATTERN_SEEDS` /
`ZLIB_SEEDS` below (also echoed into `testdata/golden/MANIFEST.md`). Re-running
this script must reproduce byte-identical output.

Usage:
    python3 testdata/py/gen_golden.py

Regenerates every file under `testdata/golden/` and refreshes
`testdata/corpus/pngsuite-truth/` (skipped with a warning if the corpus isn't
vendored). Nothing here touches `testdata/golden/netpbm/` or
`testdata/golden/bmp/` as directories — those are owned by other work
packages; this script's own BMP/PPM/PGM outputs live flat under
`testdata/golden/` instead (see MANIFEST.md).
"""
from __future__ import annotations

import io
import random
import sys
import zlib
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
import praw  # noqa: E402
import pngsuite_truth  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent  # testdata/
GOLDEN = ROOT / "golden"
ZLIB_DIR = GOLDEN / "zlib"

# ---------------------------------------------------------------------------
# Seeds (recorded here AND in MANIFEST.md — the two must be kept in sync;
# MANIFEST.md is regenerated by this script's final step from this table).
# ---------------------------------------------------------------------------

PATTERN_SEEDS = {
    "hgradient": 1001,
    "vgradient": 1002,
    "checker8": 1003,
    "noise": 1004,
    "flat": 1005,
    "fewcolors": 1006,
}
PHOTO_SEED = 1007
ANIM_SEED = 1008

ZLIB_SEEDS = {
    "one": 2001,
    "random4k": 2002,
    "b65535": 2003,
    "b65536": 2004,
    "random100k": 2005,
}

SIZES = [(16, 16), (33, 17)]
TINY_SIZE = (1, 1)
MODES = ["l", "la", "rgb", "rgba", "p"]

# Pixel values printed at the end for hardcoding into
# Tests/RoundTripTests.lean (per the work package spec).
PRINTED_PIXELS_OF = "hgradient_rgb_16x16"
PRINTED_COORDS = [(0, 0), (15, 0), (0, 15), (15, 15), (7, 3)]


# ---------------------------------------------------------------------------
# Pattern generation: every pattern reduces to a small RGB palette plus a
# per-pixel index grid. This keeps P-mode generation exact (no Pillow
# quantization involved) and lets every other mode derive its pixel values
# directly from the same palette, so every mode variant of one pattern
# depicts the *same* image.
# ---------------------------------------------------------------------------

def gen_flat(rng: random.Random, w: int, h: int):
    color = (rng.randrange(256), rng.randrange(256), rng.randrange(256))
    idx = [[0] * w for _ in range(h)]
    return [color], idx


def gen_checker8(rng: random.Random, w: int, h: int):
    c0 = (rng.randrange(256), rng.randrange(256), rng.randrange(256))
    c1 = (rng.randrange(256), rng.randrange(256), rng.randrange(256))
    idx = [[((x // 8) + (y // 8)) % 2 for x in range(w)] for y in range(h)]
    return [c0, c1], idx


def _tint_ramp(n: int) -> list[tuple[int, int, int]]:
    """`n` deterministically-tinted (non-grayscale) ramp colors, `n<=256`.
    Never the literal identity ramp `(i,i,i)` — GIF's `_is_palette_needed`
    would then omit the color table and Pillow would reopen it as mode `L`
    instead of `P`, which would break the P-mode round-trip fixtures."""
    out = []
    for i in range(n):
        v = 255 if n <= 1 else round(i * 255 / (n - 1))
        out.append((v, (v + 85) % 256, (v + 170) % 256))
    return out


def gen_hgradient(rng: random.Random, w: int, h: int):
    del rng  # purely positional; no randomness needed
    palette = _tint_ramp(w)
    idx = [[x for x in range(w)] for _ in range(h)]
    return palette, idx


def gen_vgradient(rng: random.Random, w: int, h: int):
    del rng
    palette = _tint_ramp(h)
    idx = [[y for _ in range(w)] for y in range(h)]
    return palette, idx


def gen_noise(rng: random.Random, w: int, h: int):
    k = min(256, w * h)
    palette = [(rng.randrange(256), rng.randrange(256), rng.randrange(256)) for _ in range(k)]
    idx = [[rng.randrange(k) for _ in range(w)] for _ in range(h)]
    return palette, idx


def gen_fewcolors(rng: random.Random, w: int, h: int):
    k = min(16, max(2, 3 + rng.randrange(13)))
    palette = [(rng.randrange(256), rng.randrange(256), rng.randrange(256)) for _ in range(k)]
    idx = [[(x * 7 + y * 13) % k for x in range(w)] for y in range(h)]
    return palette, idx


PATTERNS = {
    "hgradient": gen_hgradient,
    "vgradient": gen_vgradient,
    "checker8": gen_checker8,
    "noise": gen_noise,
    "flat": gen_flat,
    "fewcolors": gen_fewcolors,
}


def luma(r: int, g: int, b: int) -> int:
    """ITU-R 601-2 luma, matching `PILean.Color.luma`'s rounded fixed-point
    formula — used only to pick our own ground-truth `L`/`LA` pixel values,
    not because Pillow needs it (we build `L`/`LA` images directly)."""
    return (r * 19595 + g * 38470 + b * 7471 + 0x8000) >> 16


def alpha_at(x: int, y: int, pattern: str) -> int:
    """Deterministic per-pixel alpha for `LA`/`RGBA` variants: constant
    (opaque) for `flat` so at least one fixture has no alpha variation,
    a smooth function of position otherwise."""
    if pattern == "flat":
        return 255
    return (x * 31 + y * 17 + 7) % 256


def build_mode_bytes(mode: str, palette, idx, w: int, h: int, pattern: str) -> bytes:
    out = bytearray()
    if mode == "l":
        for y in range(h):
            for x in range(w):
                r, g, b = palette[idx[y][x]]
                out.append(luma(r, g, b))
    elif mode == "la":
        for y in range(h):
            for x in range(w):
                r, g, b = palette[idx[y][x]]
                out.append(luma(r, g, b))
                out.append(alpha_at(x, y, pattern))
    elif mode == "rgb":
        for y in range(h):
            for x in range(w):
                out += bytes(palette[idx[y][x]])
    elif mode == "rgba":
        for y in range(h):
            for x in range(w):
                r, g, b = palette[idx[y][x]]
                out += bytes((r, g, b, alpha_at(x, y, pattern)))
    elif mode == "p":
        for y in range(h):
            for x in range(w):
                out.append(idx[y][x])
    else:
        raise ValueError(mode)
    return bytes(out)


def build_image(mode: str, palette, idx, w: int, h: int, pattern: str) -> Image.Image:
    data = build_mode_bytes(mode, palette, idx, w, h, pattern)
    if mode == "l":
        return Image.frombytes("L", (w, h), data)
    if mode == "la":
        return Image.frombytes("LA", (w, h), data)
    if mode == "rgb":
        return Image.frombytes("RGB", (w, h), data)
    if mode == "rgba":
        return Image.frombytes("RGBA", (w, h), data)
    if mode == "p":
        im = Image.frombytes("P", (w, h), data)
        flat_palette = bytearray()
        for (r, g, b) in palette:
            flat_palette += bytes((r, g, b))
        im.putpalette(bytes(flat_palette), rawmode="RGB")
        return im
    raise ValueError(mode)


# ---------------------------------------------------------------------------
# Per-base-image file emission
# ---------------------------------------------------------------------------

generated_files: list[str] = []


def _write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    generated_files.append(str(path.relative_to(GOLDEN)))


def emit_base_image(name: str, im: Image.Image, mode: str) -> None:
    """Write `<name>.praw` (ground truth) plus every natural encoding of
    `im` for its mode: PNG always; BMP for l/rgb/p; PGM for l; PPM for rgb;
    GIF (+ a tRNS-transparency PNG variant) for p.

    BMP is *not* generated for `rgba`: Pillow's own 32bpp BMP writer always
    emits a plain 40-byte `BITMAPINFOHEADER` with no alpha bitmask
    (`PIL.BmpImagePlugin.SAVE["RGBA"]` writes `BGRA` pixel bytes but never
    the `BITMAPV4HEADER`/`BITMAPV5HEADER` needed to *declare* the 4th byte
    as alpha), so Pillow's own reader — and any spec-conformant BMP reader
    — opens it back as plain `RGB`, silently discarding alpha. Verified
    empirically: `Image.open(rgba_bmp_bytes).mode == "RGB"`. An "exact
    pixel" oracle fixture would therefore be comparing against data Pillow
    itself cannot round-trip, so it's skipped rather than encoding a
    misleading exactness claim."""
    m, w, h, data, palette = praw.image_to_praw_args(im)
    praw.write_praw(GOLDEN / f"{name}.praw", m, w, h, data, palette)
    generated_files.append(f"{name}.praw")

    buf = io.BytesIO()
    im.save(buf, "PNG")
    _write(GOLDEN / f"{name}.png", buf.getvalue())

    if mode in ("l", "rgb", "p"):
        buf = io.BytesIO()
        im.save(buf, "BMP")
        _write(GOLDEN / f"{name}.bmp", buf.getvalue())

    if mode == "l":
        buf = io.BytesIO()
        im.save(buf, "PPM")  # Pillow writes P5 (pgm) for L automatically
        _write(GOLDEN / f"{name}.pgm", buf.getvalue())

    if mode == "rgb":
        buf = io.BytesIO()
        im.save(buf, "PPM")
        _write(GOLDEN / f"{name}.ppm", buf.getvalue())

    if mode == "p":
        buf = io.BytesIO()
        im.save(buf, "GIF")
        _write(GOLDEN / f"{name}.gif", buf.getvalue())


def emit_p_transparency(name: str, palette, idx, w: int, h: int, pattern: str) -> None:
    """A second P-mode variant of the same index grid with a full per-index
    alpha table (tRNS), as its own named fixture (own .praw truth + .png)."""
    im = build_image("p", palette, idx, w, h, pattern)
    n = im.getpalette()
    n = len(n) // 3 if n else 0
    alphas = bytes((i * 53 + 29) % 256 for i in range(n))
    im.info["transparency"] = alphas

    tname = f"{name}_transparency"
    m, w2, h2, data, pal = praw.image_to_praw_args(im)
    praw.write_praw(GOLDEN / f"{tname}.praw", m, w2, h2, data, pal)
    generated_files.append(f"{tname}.praw")

    buf = io.BytesIO()
    im.save(buf, "PNG")
    _write(GOLDEN / f"{tname}.png", buf.getvalue())


def gen_pattern_matrix() -> tuple[Image.Image, int, int] | None:
    """Generate every (pattern, mode, size) fixture. Returns
    `(image, width, height)` for `PRINTED_PIXELS_OF`, needed for
    `Tests/RoundTripTests.lean`'s hardcoded assertions."""
    printed = None
    # 1x1 is only meaningful for `flat` (every other pattern degenerates to
    # a single arbitrary pixel indistinguishable from `flat` at this size).
    for pattern, fn in PATTERNS.items():
        seed = PATTERN_SEEDS[pattern]
        rng = random.Random(seed)
        sizes = SIZES + ([TINY_SIZE] if pattern == "flat" else [])
        for (w, h) in sizes:
            palette, idx = fn(rng, w, h)
            for mode in MODES:
                name = f"{pattern}_{mode}_{w}x{h}"
                im = build_image(mode, palette, idx, w, h, pattern)
                emit_base_image(name, im, mode)
                if mode == "p":
                    emit_p_transparency(name, palette, idx, w, h, pattern)
                if name == PRINTED_PIXELS_OF:
                    printed = (im, w, h)
    return printed


def gen_photo_jpeg() -> None:
    """One RGB "photo-ish" pattern (smooth gradient + noise), encoded as
    JPEG at three quality levels, plus its RGB source-of-truth .praw for
    PSNR comparison (JPEG is lossy, so crosscheck compares by PSNR, not
    exact bytes).

    Size 64×64 and noise amplitude ±2 are deliberately tuned (not
    arbitrary): JPEG's 8×8-block DCT quantization at quality 10 is harsh
    enough that a *tiny* image (the pattern matrix's usual 33×17) or
    stronger noise (±20) pushes even quality-10 PSNR below the crosscheck
    threshold of 30 dB — verified empirically across several sizes/
    amplitudes. 64×64 + ±2 clears 30 dB at q10 with a comfortable margin
    while still exercising all three quality levels meaningfully
    (q10≈30.6 dB, q75≈41.2 dB, q95≈43.8 dB against this exact seed)."""
    rng = random.Random(PHOTO_SEED)
    w, h = 64, 64
    noise_amp = 2

    def clip(v: int) -> int:
        return 0 if v < 0 else 255 if v > 255 else v

    data = bytearray()
    for y in range(h):
        for x in range(w):
            r = clip(x * 255 // (w - 1) + rng.randint(-noise_amp, noise_amp))
            g = clip(y * 255 // (h - 1) + rng.randint(-noise_amp, noise_amp))
            b = clip((x + y) * 255 // (w + h - 2) + rng.randint(-noise_amp, noise_amp))
            data += bytes((r, g, b))
    im = Image.frombytes("RGB", (w, h), bytes(data))

    name = f"photo_rgb_{w}x{h}"
    m, ww, hh, praw_data, _ = praw.image_to_praw_args(im)
    praw.write_praw(GOLDEN / f"{name}.praw", m, ww, hh, praw_data, None)
    generated_files.append(f"{name}.praw")

    for q in (10, 75, 95):
        buf = io.BytesIO()
        im.save(buf, "JPEG", quality=q)
        _write(GOLDEN / f"{name}_q{q}.jpg", buf.getvalue())


def gen_animated_gif() -> None:
    """One 3-frame animated GIF made of a checker pattern shifted each
    frame. No matching .praw truth (crosscheck.py skips files with none) —
    this fixture exists to exercise PILean's GIF *multi-frame* handling,
    not the single-frame pixel oracle."""
    rng = random.Random(ANIM_SEED)
    w, h = 16, 16
    c0 = (rng.randrange(256), rng.randrange(256), rng.randrange(256))
    c1 = (rng.randrange(256), rng.randrange(256), rng.randrange(256))
    frames = []
    for shift in range(3):
        data = bytearray()
        for y in range(h):
            for x in range(w):
                data.append((((x + shift * 3) // 8) + (y // 8)) % 2)
        im = Image.frombytes("P", (w, h), bytes(data))
        im.putpalette(bytes((c0[0], c0[1], c0[2], c1[0], c1[1], c1[2])), rawmode="RGB")
        frames.append(im)
    buf = io.BytesIO()
    frames[0].save(buf, "GIF", save_all=True, append_images=frames[1:], loop=0, duration=100)
    _write(GOLDEN / "checker_anim.gif", buf.getvalue())


# ---------------------------------------------------------------------------
# zlib corpus
# ---------------------------------------------------------------------------

TEXT_PARAGRAPH = (
    "The quick brown fox jumps over the lazy dog while the zlib deflate "
    "window slides across a stream of repeated English prose, testing "
    "match-finding at every offset it can reach. "
)


def zlib_corpus_data() -> dict[str, bytes]:
    data = {}
    data["empty"] = b""
    data["one"] = random.Random(ZLIB_SEEDS["one"]).randbytes(1)
    data["zeros"] = b"\x00" * 4096
    data["random4k"] = random.Random(ZLIB_SEEDS["random4k"]).randbytes(4096)
    text = (TEXT_PARAGRAPH * (20480 // len(TEXT_PARAGRAPH) + 1))[:20480]
    data["text"] = text.encode("ascii")
    data["b65535"] = random.Random(ZLIB_SEEDS["b65535"]).randbytes(65535)
    data["b65536"] = random.Random(ZLIB_SEEDS["b65536"]).randbytes(65536)
    # Spec suggested 200 KB; trimmed to 100 KB to keep testdata/golden under
    # the ~4 MB budget (random data is incompressible, so 10 zlib levels +
    # raw9 + bin each cost ~the full size — see MANIFEST.md).
    data["random100k"] = random.Random(ZLIB_SEEDS["random100k"]).randbytes(100_000)
    return data


def gen_zlib_corpus() -> None:
    for cls, raw in zlib_corpus_data().items():
        _write(ZLIB_DIR / f"{cls}.bin", raw)
        for level in range(10):
            _write(ZLIB_DIR / f"{cls}.z{level}", zlib.compress(raw, level))
        co = zlib.compressobj(9, zlib.DEFLATED, -15)
        raw9 = co.compress(raw) + co.flush()
        _write(ZLIB_DIR / f"{cls}.raw9", raw9)


# ---------------------------------------------------------------------------
# MANIFEST.md
# ---------------------------------------------------------------------------

def write_manifest(printed_pixels: list[tuple[int, int, tuple]]) -> None:
    import PIL

    lines = []
    lines.append("# testdata/golden — provenance and regeneration")
    lines.append("")
    lines.append("Generated by `testdata/py/gen_golden.py`. Goldens are checked in and never")
    lines.append("regenerated in CI — only by re-running this script by hand and reviewing")
    lines.append("the diff.")
    lines.append("")
    lines.append("## Versions")
    lines.append("")
    lines.append(f"- Python: `{sys.version.split()[0]}`")
    lines.append(f"- Pillow: `{PIL.__version__}` (pin: 11.3.0)")
    lines.append(f"- zlib (Python's `zlib` module): `{zlib.ZLIB_VERSION}`")
    lines.append("")
    lines.append("## Regeneration")
    lines.append("")
    lines.append("```sh")
    lines.append("python3 testdata/py/gen_golden.py       # rewrites testdata/golden/** and")
    lines.append("                                      # testdata/corpus/pngsuite-truth/**")
    lines.append("python3 testdata/py/crosscheck.py        # verify PILean's own output later")
    lines.append("```")
    lines.append("")
    lines.append("## Pattern matrix seeds")
    lines.append("")
    lines.append("One `random.Random(seed)` per pattern name, threaded through both sizes")
    lines.append("(16×16 then 33×17, in that order; `flat` additionally does 1×1 last) in")
    lines.append("a fixed loop order — reseeded only at the start of each pattern, per the")
    lines.append("work package spec (\"random.Random(seed) per pattern\").")
    lines.append("")
    lines.append("| pattern | seed |")
    lines.append("|---|---|")
    for k, v in PATTERN_SEEDS.items():
        lines.append(f"| {k} | {v} |")
    lines.append(f"| photo (JPEG source) | {PHOTO_SEED} |")
    lines.append(f"| checker_anim.gif | {ANIM_SEED} |")
    lines.append("")
    lines.append("`hgradient`/`vgradient` are deterministic ramps needing no randomness "
                  "(the `rng` parameter is accepted but unused, to keep a uniform pattern "
                  "function signature).")
    lines.append("")
    lines.append("Sizes: 16×16 and 33×17 for every pattern × mode (l, la, rgb, rgba, p); "
                  "1×1 only for `flat` (the only pattern that isn't visually degenerate at "
                  "a single pixel — checker/gradient/noise/fewcolors would just look like "
                  "`flat` there too, so those combinations are skipped).")
    lines.append("")
    lines.append("P-mode images additionally get a `<name>_transparency.{praw,png}` "
                  "variant: same index grid, palette alpha `(i*53+29) % 256` per index "
                  "`i`, written as a PNG tRNS chunk.")
    lines.append("")
    lines.append("`.bmp` is generated for `l`/`rgb`/`p` only, **not** `rgba`: Pillow's own "
                  "32bpp BMP writer never declares an alpha bitmask, so Pillow's own reader "
                  "(and any conformant BMP reader) opens the result back as plain `RGB`, "
                  "silently dropping alpha — verified empirically. An RGBA BMP fixture "
                  "would be an \"exact\" oracle for data Pillow itself cannot round-trip, "
                  "so it's skipped. `.gif`'s global color table must be a power-of-two "
                  "size, so Pillow zero-pads P-mode palettes on write; `crosscheck.py` "
                  "accordingly only requires the *first* `len(truth palette)` GIF palette "
                  "entries to match, not the padding.")
    lines.append("")
    lines.append("## JPEG photo pattern")
    lines.append("")
    lines.append(f"`photo_rgb_64x64` — smooth diagonal RGB gradient (`x`, `y`, `x+y` ramps) "
                  "plus `randint(-2, 2)` per-channel noise, seed "
                  f"{PHOTO_SEED}. Encoded at quality 10/75/95. JPEG is lossy — "
                  "`crosscheck.py` compares by PSNR (≥ 30 dB) against `photo_rgb_64x64.praw`, "
                  "not exact bytes. Size and noise amplitude are tuned so quality-10 clears "
                  "30 dB with margin — a tiny image or stronger noise pushes even "
                  "quality-10 JPEG below the threshold on pure block-quantization loss "
                  "alone (verified empirically; see the generator's docstring).")
    lines.append("")
    lines.append("## Animated GIF")
    lines.append("")
    lines.append(f"`checker_anim.gif` — 3 frames, an 8×8 checkerboard (seed {ANIM_SEED} for "
                  "its two colors) shifted 3px horizontally per frame. No `.praw` truth "
                  "(multi-frame; `crosscheck.py` skips files with no matching golden "
                  "with a warning) — exists to exercise multi-frame GIF decoding.")
    lines.append("")
    lines.append("## zlib corpus (`testdata/golden/zlib/`)")
    lines.append("")
    lines.append("Each data class `<class>` is written as `<class>.bin` (raw), "
                  "`<class>.z0` … `<class>.z9` (`zlib.compress(data, level)` for level "
                  "0–9), and `<class>.raw9` (`zlib.compressobj(9, zlib.DEFLATED, "
                  "wbits=-15)` — a raw, headerless deflate stream at level 9).")
    lines.append("")
    lines.append("| class | size | seed | notes |")
    lines.append("|---|---|---|---|")
    lines.append("| empty | 0 B | — | |")
    lines.append(f"| one | 1 B | {ZLIB_SEEDS['one']} | |")
    lines.append("| zeros | 4096 B | — | all `\\x00` |")
    lines.append(f"| random4k | 4096 B | {ZLIB_SEEDS['random4k']} | |")
    lines.append("| text | 20480 B | — | repeated English paragraph (see script) |")
    lines.append(f"| b65535 | 65535 B | {ZLIB_SEEDS['b65535']} | one byte short of the 64 KiB "
                  "DEFLATE stored-block boundary |")
    lines.append(f"| b65536 | 65536 B | {ZLIB_SEEDS['b65536']} | exactly the 64 KiB boundary |")
    lines.append(f"| random100k | 100000 B | {ZLIB_SEEDS['random100k']} | **trimmed from the "
                  "spec's suggested 200 KB** — random data is incompressible, so all 12 "
                  "variants (bin + 10 levels + raw9) cost ~the full size each; 200 KB would "
                  "have used ~2.4 MB alone. 100 KB keeps `testdata/golden` comfortably under "
                  "the ~4 MB budget. |")
    lines.append("")
    lines.append("## PngSuite corpus")
    lines.append("")
    lines.append("Vendored under `testdata/corpus/pngsuite/` (separate from the ~4 MB "
                  "`testdata/golden` budget — see `testdata/corpus/pngsuite/README.md` for "
                  "provenance, license, and the corrupt-file list). Pixel truth is "
                  "generated into `testdata/corpus/pngsuite-truth/*.praw` by "
                  "`testdata/py/pngsuite_truth.py` (invoked automatically by this script) — "
                  "see that script's module docstring for PILean's exact 16-bit-to-8-bit "
                  "normalization rules.")
    lines.append("")
    lines.append("- Source: `http://www.schaik.com/pngsuite2011/PngSuite-2017jul19.tgz`")
    lines.append("- Downloaded: 2026-07-11")
    lines.append("")
    lines.append("## Hardcoded pixel values for `Tests/RoundTripTests.lean`")
    lines.append("")
    lines.append(f"From `{PRINTED_PIXELS_OF}.praw` (also committed as the fixture itself):")
    lines.append("")
    lines.append("| (x, y) | RGB |")
    lines.append("|---|---|")
    for (x, y), rgb in printed_pixels:
        lines.append(f"| ({x}, {y}) | {rgb} |")
    lines.append("")
    lines.append("## Full file list")
    lines.append("")
    lines.append(f"{len(generated_files)} files generated by the most recent run of this "
                  "script (excluding this MANIFEST itself). Re-run "
                  "`python3 testdata/py/gen_golden.py` to regenerate; diff `git status` "
                  "afterward to confirm no unexpected changes.")
    lines.append("")

    (GOLDEN / "MANIFEST.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    GOLDEN.mkdir(parents=True, exist_ok=True)
    ZLIB_DIR.mkdir(parents=True, exist_ok=True)

    printed_image = gen_pattern_matrix()
    gen_photo_jpeg()
    gen_animated_gif()
    gen_zlib_corpus()

    printed_pixels = []
    if printed_image is not None:
        im, w, h = printed_image
        for (x, y) in PRINTED_COORDS:
            if x < w and y < h:
                printed_pixels.append(((x, y), im.getpixel((x, y))))
    write_manifest(printed_pixels)

    corpus_dir = ROOT / "corpus" / "pngsuite"
    truth_dir = ROOT / "corpus" / "pngsuite-truth"
    if corpus_dir.exists() and any(corpus_dir.glob("*.png")):
        generated, skipped = pngsuite_truth.generate(corpus_dir, truth_dir)
        print(f"pngsuite_truth: wrote {generated} truth .praw files "
              f"({skipped} corrupt skipped)")
    else:
        print(f"pngsuite_truth: no vendored corpus at {corpus_dir}, skipping", file=sys.stderr)

    total_bytes = sum((GOLDEN / f).stat().st_size for f in generated_files)
    print(f"gen_golden: wrote {len(generated_files)} files under {GOLDEN} "
          f"({total_bytes / 1024:.1f} KiB)")
    print(f"\nHardcode these into Tests/RoundTripTests.lean "
          f"(fixture {PRINTED_PIXELS_OF}.praw):")
    for (x, y), rgb in printed_pixels:
        print(f"  ({x}, {y}) -> {rgb}")


if __name__ == "__main__":
    main()
