import PILean.Codec.Types
import PILean.Binary.Reader
import PILean.Codec.Png.Chunk
import PILean.Codec.Png.Filter
import PILean.Codec.Png.Interlace
import PILean.Compress.Zlib

/-!
# PNG decoding

WP12. Pipeline: `readChunks` (signature + per-chunk CRC-32, already
verified by `Chunk.lean`) → parse and validate `IHDR` → collect
`PLTE`/`tRNS`/ancillaries and concatenate every `IDAT` payload →
`Zlib.decompress` → unfilter (Adam7-aware) → unpack/normalize to
PILean's storage layout → `Image`.

## Normalization policy (must match `testdata/corpus/pngsuite-truth/*.praw`,
generated by `testdata/py/pngsuite_truth.py`)

* Grayscale/palette bit depths 1/2/4 scale to 8-bit via
  `Interlace.scaleSample` (palette indices are left raw, never scaled).
* Any 16-bit channel (gray, rgb, grayAlpha, rgba) takes the high byte —
  truncated, never rounded.
* Color type 3 (palette): entries come from `PLTE`; a `tRNS` chunk folds
  per-index alpha into the RGBA palette (missing trailing entries default
  to opaque). Every decoded pixel index is checked against the palette
  size — an out-of-range index is `corrupt` rather than a later panic in
  `Palette.get!`.
* Color types 0/2 (gray/rgb) with a `tRNS` chunk: pixels are **not**
  altered (no color-key transparency is applied); the raw chunk value is
  recorded in `Image.info` under key `"tRNS"` instead (gray: one decimal
  sample; rgb: `"r,g,b"`, all as the raw 16-bit-per-sample values the
  chunk stores, matching Pillow's `chunk_tRNS`).
* Adam7 (`interlace = 1`): fully deinterlaced by `Png.Interlace.deinterlace`
  — decode-only, the encoder never interlaces.
* Ancillary chunks `tEXt`/`zTXt`/`tIME`/`gAMA`/`pHYs` parse into
  `Image.info` as string key/value pairs (`zTXt`'s text is
  zlib-decompressed first; `gAMA`'s value is the raw 100000-scaled
  integer, as a string, per the work package spec — not Pillow's derived
  float). Any other ancillary chunk (lowercase first type letter) is
  skipped silently; any *unknown critical* chunk (uppercase first type
  letter, not `IHDR`/`PLTE`/`IDAT`/`IEND`) is `DecodeError.unsupported`.
* Malformed anything — bad `IHDR` combinations, a missing/absent `PLTE`
  for color type 3, no `IDAT` data at all, a zlib failure, an unfiltered
  size that doesn't match the declared dimensions, truncation anywhere —
  is a `DecodeError`, never a panic or a hang.
-/

namespace PILean.Png

open PILean.Binary
open PILean.Compress.Zlib (decompress)

/-- Parsed and validated `IHDR` fields (all in `Nat` for arithmetic
convenience with `Interlace`'s helpers). -/
private structure Ihdr where
  width : Nat
  height : Nat
  bitDepth : Nat
  colorType : Nat
  interlace : Nat

/-- Bit depths the PNG spec allows for each color type; `[]` for an
invalid color type. -/
private def validBitDepths : Nat → List Nat
  | 0 => [1, 2, 4, 8, 16]
  | 2 => [8, 16]
  | 3 => [1, 2, 4, 8]
  | 4 => [8, 16]
  | 6 => [8, 16]
  | _ => []

/-- Parse and validate the 13-byte `IHDR` payload: width/height ≥ 1, the
bit-depth/color-type validity matrix, compression method 0, filter method
0, interlace method 0 or 1. -/
private def ihdrParser : ParseM Ihdr := do
  let w ← ParseM.u32be
  let h ← ParseM.u32be
  let bd ← ParseM.u8
  let ct ← ParseM.u8
  let comp ← ParseM.u8
  let filt ← ParseM.u8
  let il ← ParseM.u8
  unless (← ParseM.isEof) do
    throw (.corrupt (← ParseM.pos) "IHDR: payload has extra trailing bytes")
  if w == 0 then throw (.corrupt 8 "IHDR: width must be ≥ 1")
  if h == 0 then throw (.corrupt 8 "IHDR: height must be ≥ 1")
  if comp != 0 then throw (.corrupt 10 s!"IHDR: unsupported compression method {comp}")
  if filt != 0 then throw (.corrupt 11 s!"IHDR: unsupported filter method {filt}")
  if il > 1 then throw (.corrupt 12 s!"IHDR: unsupported interlace method {il}")
  let depths := validBitDepths ct.toNat
  if depths.isEmpty then
    throw (.corrupt 9 s!"IHDR: invalid color type {ct}")
  unless depths.contains bd.toNat do
    throw (.corrupt 8 s!"IHDR: invalid bit depth {bd} for color type {ct}")
  return { width := w.toNat, height := h.toNat, bitDepth := bd.toNat,
           colorType := ct.toNat, interlace := il.toNat }

/-- Parse the `IHDR` chunk's payload (must be exactly 13 bytes). -/
private def parseIhdr (payload : ByteArray) : Except DecodeError Ihdr :=
  if payload.size != 13 then
    .error (.corrupt 0 s!"IHDR: payload must be 13 bytes, got {payload.size}")
  else
    ParseM.run ihdrParser payload

/-- Is the ASCII first byte of a 4-character chunk type uppercase (i.e. is
this a *critical* chunk, per the PNG spec's chunk-name bit convention)? -/
private def isCriticalChunk (typ : String) : Bool :=
  match typ.toList with
  | c :: _ => (c.toNat / 32) % 2 == 0
  | [] => false

/-- The four chunk types every PNG decoder must understand. -/
private def isKnownCriticalName (typ : String) : Bool :=
  typ == "IHDR" || typ == "PLTE" || typ == "IDAT" || typ == "IEND"

/-- Decode `n` raw bytes as a Latin-1 string (PNG text chunks are Latin-1;
every byte 0–255 is a valid `Char` code point, so this never fails). -/
private def latin1ToString (b : ByteArray) : String := Id.run do
  let mut s := ""
  for i in [0:b.size] do
    s := s.push (Char.ofNat (b.get! i).toNat)
  return s

/-- Offset of the first occurrence of `target` in `b`, if any. -/
private def findByte (b : ByteArray) (target : UInt8) : Option Nat := Id.run do
  let mut result : Option Nat := none
  for i in [0:b.size] do
    if b.get! i == target then
      result := some i
      break
  return result

/-- Big-endian bytes-to-`Nat` via plain multiplication (no `Nat`-level
bitwise ops, per this codebase's convention). -/
private def beNat (bs : ByteArray) : Nat := Id.run do
  let mut acc := 0
  for i in [0:bs.size] do
    acc := acc * 256 + (bs.get! i).toNat
  return acc

/-- `tEXt`: `keyword\0text`, both Latin-1. `none` if there is no
terminating NUL. -/
private def parseTextChunk (payload : ByteArray) : Option (String × String) :=
  match findByte payload 0 with
  | none => none
  | some idx =>
    some (latin1ToString (payload.extract 0 idx), latin1ToString (payload.extract (idx + 1) payload.size))

/-- `zTXt`: `keyword\0 compressionMethod compressedText`. `compressionMethod`
must be 0 (zlib/DEFLATE, the PNG spec's only defined method); the text is
then `Zlib.decompress`ed. `none` on any structural or zlib failure — a
malformed ancillary chunk is skipped, not a whole-file decode failure. -/
private def parseZtxtChunk (payload : ByteArray) : Option (String × String) :=
  match findByte payload 0 with
  | none => none
  | some idx =>
    if idx + 1 ≥ payload.size then none
    else if payload.get! (idx + 1) != 0 then none
    else
      match decompress (payload.extract (idx + 2) payload.size) with
      | .error _ => none
      | .ok text => some (latin1ToString (payload.extract 0 idx), latin1ToString text)

/-- `gAMA`: a single big-endian `u32`, gamma × 100000. Stored as the raw
integer's decimal string (per the work package spec), not Pillow's
derived float. -/
private def parseGamaChunk (payload : ByteArray) : Option (String × String) :=
  if payload.size != 4 then none
  else some ("gAMA", toString (beNat payload))

/-- `pHYs`: pixels-per-unit X, pixels-per-unit Y (both big-endian `u32`),
then a 1-byte unit (`0` unknown, `1` meter). Stored as `"x,y,unit"`. -/
private def parsePhysChunk (payload : ByteArray) : Option (String × String) :=
  if payload.size != 9 then none
  else
    let x := beNat (payload.extract 0 4)
    let y := beNat (payload.extract 4 8)
    some ("pHYs", s!"{x},{y},{payload.get! 8}")

/-- `tIME`: year (`u16be`), month, day, hour, minute, second (each `u8`).
Stored as `"YYYY-MM-DD HH:MM:SS"`. -/
private def parseTimeChunk (payload : ByteArray) : Option (String × String) :=
  if payload.size != 7 then none
  else
    let year := beNat (payload.extract 0 2)
    some ("tIME",
      s!"{year}-{payload.get! 2}-{payload.get! 3} {payload.get! 4}:{payload.get! 5}:{payload.get! 6}")

/-- `tRNS` on color type 0 (gray) or 2 (rgb): the chunk's raw 16-bit-per-
sample value(s) — gray as one decimal number, rgb as `"r,g,b"` — matching
what Pillow's `chunk_tRNS` records (pixels are left untouched; this is
metadata only). `none` for any other color type or a malformed payload. -/
private def parseTrnsInfo (colorType : Nat) (payload : ByteArray) : Option (String × String) :=
  match colorType with
  | 0 =>
    if payload.size < 2 then none else some ("tRNS", toString (beNat (payload.extract 0 2)))
  | 2 =>
    if payload.size < 6 then none
    else
      let r := beNat (payload.extract 0 2)
      let g := beNat (payload.extract 2 4)
      let b := beNat (payload.extract 4 6)
      some ("tRNS", s!"{r},{g},{b}")
  | _ => none

/-- Build the RGBA palette for color type 3 from `PLTE` (3 bytes/entry,
1–256 entries) and an optional `tRNS` (1 alpha byte per index, missing
trailing entries default to opaque `255`). -/
private def buildPalette (plte : ByteArray) (trns? : Option ByteArray) : Except DecodeError Palette := do
  if plte.size % 3 != 0 then
    throw (.corrupt 0 s!"PLTE: payload size {plte.size} is not a multiple of 3")
  let n := plte.size / 3
  if n == 0 || n > 256 then
    throw (.corrupt 0 s!"PLTE: {n} entries (must be 1..256)")
  let mut p : Palette := { entries := ByteArray.emptyWithCapacity (4 * n) }
  for i in [0:n] do
    let a := match trns? with
      | some t => if i < t.size then t.get! i else 255
      | none => 255
    p := p.push (Color.rgba (plte.get! (3 * i)) (plte.get! (3 * i + 1)) (plte.get! (3 * i + 2)) a)
  return p

/-- Decode a PNG. See the module docstring for the full normalization
policy; never panics or hangs on malformed input. -/
def decode (bytes : ByteArray) : Except DecodeError Image := do
  let chunks ← readChunks bytes
  if chunks.size == 0 || chunks[0]!.typ != "IHDR" then
    throw (.corrupt 0 "PNG: first chunk is not IHDR")
  for c in chunks do
    if isCriticalChunk c.typ && !isKnownCriticalName c.typ then
      throw (.unsupported "png" s!"unknown critical chunk {c.typ}")
  let ihdr ← parseIhdr chunks[0]!.data
  -- `validBitDepths`/`ihdrParser` already reject any color type not in
  -- `{0,2,3,4,6}`, so `modeOf` is total by construction here.
  let mode ← match modeOf ihdr.colorType ihdr.bitDepth with
    | some m => pure m
    | none => throw (.corrupt 0 s!"unreachable: IHDR already validated color type {ihdr.colorType}")
  let mut idat := ByteArray.empty
  let mut plte? : Option ByteArray := none
  let mut trns? : Option ByteArray := none
  let mut info : List (String × String) := []
  for c in chunks do
    match c.typ with
    | "IDAT" => idat := idat ++ c.data
    | "PLTE" => if plte?.isNone then plte? := some c.data
    | "tRNS" => if trns?.isNone then trns? := some c.data
    | "tEXt" => if let some kv := parseTextChunk c.data then info := info ++ [kv]
    | "zTXt" => if let some kv := parseZtxtChunk c.data then info := info ++ [kv]
    | "tIME" => if let some kv := parseTimeChunk c.data then info := info ++ [kv]
    | "gAMA" => if let some kv := parseGamaChunk c.data then info := info ++ [kv]
    | "pHYs" => if let some kv := parsePhysChunk c.data then info := info ++ [kv]
    | _ => pure ()
  if ihdr.colorType == 0 || ihdr.colorType == 2 then
    if let some t := trns? then
      if let some kv := parseTrnsInfo ihdr.colorType t then
        info := info ++ [kv]
  if ihdr.colorType == 3 && plte?.isNone then
    throw (.corrupt 0 "PNG: color type 3 (palette) requires a PLTE chunk")
  if idat.isEmpty then
    throw (.corrupt 0 "PNG: no IDAT chunks (missing pixel data)")
  let raw ← decompress idat
  let normalized ←
    if ihdr.interlace == 0 then
      let bpp := bppForFilter ihdr.colorType ihdr.bitDepth
      let rowBytes := packedBytesPerRow ihdr.colorType ihdr.bitDepth ihdr.width
      let expected := ihdr.height * (1 + rowBytes)
      if raw.size != expected then
        throw (.corrupt raw.size
          s!"PNG: unfiltered data size {raw.size} bytes does not match expected {expected}")
      let unfiltered ← unfilterScanlines bpp rowBytes raw
      pure (unpackRaster ihdr.colorType ihdr.bitDepth ihdr.width ihdr.height unfiltered)
    else
      deinterlace ihdr.colorType ihdr.bitDepth ihdr.width ihdr.height raw
  -- `plte?` is `some` here whenever `colorType == 3` (checked above);
  -- `getD` is just to keep this total.
  let palette? ←
    if ihdr.colorType == 3 then
      let pal ← buildPalette (plte?.getD ByteArray.empty) trns?
      for i in [0:normalized.size] do
        let idx := normalized.get! i
        if idx.toNat ≥ pal.size then
          throw (.corrupt i s!"PNG: palette index {idx} out of range (palette has {pal.size} entries)")
      pure (some pal)
    else
      pure none
  return { width := ihdr.width, height := ihdr.height, mode, data := normalized, palette?, info }

end PILean.Png
